(require 'lts)
(lts.ruleset
net_ar
( (EmphCons s t d z) )
(
;; LTS rules
;; Emphatic vowels
;( EmphCons % [ aa ] = aa. )
( EmphCons % [ a ] = ah )
( EmphCons % [ i ] = ih )
( EmphCons % [ u ] = uh )
( EmphCons % [ A ] = ah: )
( EmphCons % [ I ] = ih: )
( EmphCons % [ U ] = uh: )
;; Vowels
( [ a ] = a )
;([a]=a)
([ i ] = i)
([ u ] = u)
([ A ] = a:)
([ I ] = i:)
([ U ] = u:)
;; Emphatic Consonants
( [ s % ] = sa)
( [ t % ] = ta )
( [ d % ] = da )
( [ z % ] = zh )
;;Consonants
([ ? ] = ?)
([ b ] = b)
([ t ] = t)
([ T ] = th)
([ Z ] = j)
([ X ] = ha)
([ x ] = kh)
([ d ] = d)
([ D ] = dh)
([ r ] = r)
([ z ] = z)
([ s ] = s)
([ S ] = sh)
([ H ] = ha)
([ G ] = gh)
([ f ] = f)
([ q ] = q)
([ k ] = k)
([ l ] = l)
([ m ] = m)
([ n ] = n)
([ h ] = h)
([ w ] = w)
([ y ] = y)
([ g ] = g)
([ p ] = p)
([ v ] = v)
))
(provide 'lex_lts_rules)
